# kopiuje plik ogs-commit.html dla strony

name: Kopiuj plik
on:
    push:
        branches:
         - main
         
jobs:
    copy-file:
        runs-on: ubuntu-latest
        steps:
        
            - name: Checkout Jakkret/website repo
              uses: actions/checkout@v4
              with:
                    repository: 'Jakkret/website'
                    path: 'website'    
                    
            - name: Checkout Jakkret/OpenGaduServer repo
              uses: actions/checkout@v4
              with:
                    repository: 'Jakkret/OpenGaduServer'
                    path: 'OpenGaduServer'
                    
            - name: copy ogs-commit.html from OGS to website
               run: cp OpenGaduServer/commit/ogs-commit.html website/docs/ogs-commit.html
               
            - name: git commands
               run: |
                cd website
                git config user.name "github-actions"
                git config user.email "actions@github.com"
                git add docs/ogs-commit.html
                git commit -m "AUTO: add ogs-commit.html"
                git push
                    